/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
///
import 'package:flutter/widgets.dart';

class MyFlutterIcons {
  MyFlutterIcons._();

  static const _kFontFam = 'MyFlutterIcons';

  static const IconData meetup = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData wordpress = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData mail = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData lamp = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData tik_tok = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData github_circled = const IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData youtube_play = const IconData(0xf16a, fontFamily: _kFontFam);
  static const IconData flickr = const IconData(0xf16e, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xf1a0, fontFamily: _kFontFam);
  static const IconData slideshare = const IconData(0xf1e7, fontFamily: _kFontFam);
  static const IconData twitch = const IconData(0xf1e8, fontFamily: _kFontFam);
  static const IconData whatsapp = const IconData(0xf232, fontFamily: _kFontFam);
  static const IconData snapchat_ghost = const IconData(0xf2ac, fontFamily: _kFontFam);
  static const IconData vimeo = const IconData(0xf306, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xf309, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf30c, fontFamily: _kFontFam);
  static const IconData pinterest = const IconData(0xf312, fontFamily: _kFontFam);
  static const IconData blogger = const IconData(0xf314, fontFamily: _kFontFam);
  static const IconData linkedin_rect = const IconData(0xf31b, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xf31e, fontFamily: _kFontFam);
  static const IconData soundcloud = const IconData(0xf348, fontFamily: _kFontFam);
}
